adv_model:
  nhid: 36
  out_dim: 12
data:
  batch_size: 4
  data_root_dir: /content/drive/MyDrive/project/cnn_input/
  dir_to_scans: dir_to_scans
  dir_to_tsv: /content/drive/MyDrive/project/datasets/files
  percentage_usage: 1.0
  val_batch_size: 2
  workers: 2
exp_name: oasis_experiment
file_name: ./saved_model/oasis_experiment
mmse_model:
  nhid: 64
model:
  arch: ours
  expansion: 8
  feature_dim: 1024
  input_channel: 1
  n_label: 3
  nhid: 512
  norm_type: Instance
  num_blocks: 0
  type_name: conv3x3x3
optimizer:
  method: SGD
  par:
    lr: 0.01
    weight_decay: 0.0
training_parameters:
  epochs: 200
  max_grad_l2_norm: null
  max_iter: 16000
  pretrain: null
  print_freq: 10
  report_interval: 100
  snapshot_interval: 1000
  start_epoch: 0
  use_age: false
visdom:
  port: 8064
  server: localhost
