NAME: CNN_ADNI

# Dataset config
DATASET: ADNI
DIR_TO_DATASET: /content/drive/MyDrive/project/cnn_input
DIR_TO_TSV: /content/drive/MyDrive/project/datasets/files
DIR_TO_LOGS: /content/drive/MyDrive/project/CNN_design_for_AD/logs
DIR_TO_SAVE_MODEL: /content/drive/MyDrive/project/CNN_design_for_AD/checkpoint

# Model architecture config
BACKBONE: simplecnn
ARCH: ours
EXPANSION: 8
FEATURE_DIM: 1024
INPUT_CHANNEL: 1
N_LABEL: 3
NHID: 512
NORM_TYPE: Instance
NUM_BLOCKS: 0
TYPE_NAME: conv3x3x3

# Optimizer config
OPTIMIZER_METHOD: SGD
LR: 0.01
WEIGHT_DECAY: 0.0
MOMENTUM: 0.9
GAMMA: 0.1
STEP_SIZE: 40

# Training config
NUM_CLASSES: 2
BATCH_SIZE: 4
VAL_BATCH_SIZE: 2
NUM_WORKERS: 2
NUM_EPOCHS: 200
SEED: 2020
PERCENTAGE_USAGE: 1.0
USE_VISDOM: False
PRINT_FREQ: 10
REPORT_INTERVAL: 100
SNAPSHOT_INTERVAL: 1000
START_EPOCH: 0

# Extra
EXP_NAME: oasis_experiment
PRETRAIN: null
MAX_ITER: 16000
USE_AGE: False
